export function countCoverage(green,roof,region=null,valid=null){if(green.length!==roof.length||region&&region.length!==roof.length||valid&&valid.length!==roof.length)throw new Error('掩膜尺寸不一致');let greenPixels=0,roofPixels=0,regionPixels=0;for(let i=0;i<roof.length;i++){if(valid&&!valid[i]||region&&!region[i])continue;regionPixels++;if(roof[i]){roofPixels++;if(green[i])greenPixels++}}return{greenPixels,roofPixels,regionPixels,roofCoverage:roofPixels?100*greenPixels/roofPixels:null,regionCoverage:regionPixels?100*greenPixels/regionPixels:null}}
export function classifyRGB(rgba,roof,{threshold=.08,nir=null,ndvi=false}={}){const out=new Uint8Array(roof.length);if(rgba.length!==roof.length*4)throw new Error('影像和屋顶范围尺寸不一致');if(ndvi&&(!nir||nir.length!==roof.length))throw new Error('缺少同尺寸近红外波段');for(let i=0;i<out.length;i++){if(!roof[i]||rgba[i*4+3]<128)continue;const r=rgba[i*4],g=rgba[i*4+1],b=rgba[i*4+2];if(ndvi){const n=nir[i];out[i]=Number.isFinite(n)&&n+r>0&&(n-r)/(n+r)>threshold?1:0}else{const sum=r+g+b;out[i]=sum>0&&(2*g-r-b)/sum>threshold&&g>r&&g>b?1:0}}return out}
export function inPolygon(x,y,p){let inside=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside}return inside}
export function polygonMask(width,height,polygons){const out=new Uint8Array(width*height);for(const p of polygons){if(p.length<3)continue;const minX=Math.max(0,Math.floor(Math.min(...p.map(v=>v[0]))*width)),maxX=Math.min(width,Math.ceil(Math.max(...p.map(v=>v[0]))*width));const minY=Math.max(0,Math.floor(Math.min(...p.map(v=>v[1]))*height)),maxY=Math.min(height,Math.ceil(Math.max(...p.map(v=>v[1]))*height));for(let y=minY;y<maxY;y++)for(let x=minX;x<maxX;x++)if(inPolygon((x+.5)/width,(y+.5)/height,p))out[y*width+x]=1}return out}
export function gridStatistics(width,height,green,roof,region,gridSize,valid){if(!Number.isInteger(gridSize)||gridSize<1)throw new Error('网格大小应为正整数');const rows=[];for(let y=0;y<height;y+=gridSize)for(let x=0;x<width;x+=gridSize){let n=0,r=0,g=0;for(let yy=y;yy<Math.min(height,y+gridSize);yy++)for(let xx=x;xx<Math.min(width,x+gridSize);xx++){const i=yy*width+xx;if(valid&&!valid[i]||region&&!region[i])continue;n++;if(roof[i]){r++;if(green[i])g++}}rows.push({id:`grid-${Math.floor(x/gridSize)+1}-${Math.floor(y/gridSize)+1}`,x,y,width:Math.min(gridSize,width-x),height:Math.min(gridSize,height-y),greenPixels:g,roofPixels:r,regionPixels:n,roofCoverage:r?g/r*100:null,regionCoverage:n?g/n*100:null})}return rows}
export function maskMetrics(predicted,truth){if(predicted.length!==truth.length)throw new Error('预测与标注尺寸不一致');let tp=0,fp=0,fn=0;for(let i=0;i<truth.length;i++){if(predicted[i]&&truth[i])tp++;else if(predicted[i])fp++;else if(truth[i])fn++}return{tp,fp,fn,f1:2*tp+fp+fn?2*tp/(2*tp+fp+fn):null,iou:tp+fp+fn?tp/(tp+fp+fn):null}}
export function buildingStatistics(width,height,green,roof,region,valid){const seen=new Uint8Array(roof.length),queue=new Int32Array(roof.length),rows=[];for(let i=0;i<roof.length;i++){if(!roof[i]||seen[i])continue;let head=0,tail=1,roofPixels=0,greenPixels=0,indices=[],xmin=width,ymin=height,xmax=0,ymax=0;queue[0]=i;seen[i]=1;while(head<tail){const k=queue[head++],x=k%width,y=Math.floor(k/width);if((!region||region[k])&&(!valid||valid[k])){roofPixels++;indices.push(k);if(green[k])greenPixels++;xmin=Math.min(xmin,x);xmax=Math.max(xmax,x);ymin=Math.min(ymin,y);ymax=Math.max(ymax,y)}for(const j of [x>0?k-1:-1,x<width-1?k+1:-1,y>0?k-width:-1,y<height-1?k+width:-1])if(j>=0&&roof[j]&&!seen[j]){seen[j]=1;queue[tail++]=j}}if(roofPixels)rows.push({id:`building-${rows.length+1}`,x:xmin,y:ymin,width:xmax-xmin+1,height:ymax-ymin+1,greenPixels,roofPixels,indices,regionPixels:roofPixels,roofCoverage:100*greenPixels/roofPixels,regionCoverage:null})}return rows}
export function brushMask(mask,width,height,x,y,radius,value,last=null){const start=last??[x,y],dist=Math.hypot(x-start[0],y-start[1]),steps=Math.max(1,Math.ceil(dist/Math.max(1,radius/2)));for(let s=0;s<=steps;s++){const cx=start[0]+(x-start[0])*s/steps,cy=start[1]+(y-start[1])*s/steps;for(let yy=Math.max(0,Math.floor(cy-radius));yy<=Math.min(height-1,Math.ceil(cy+radius));yy++)for(let xx=Math.max(0,Math.floor(cx-radius));xx<=Math.min(width-1,Math.ceil(cx+radius));xx++)if((xx-cx)**2+(yy-cy)**2<=radius**2)mask[yy*width+xx]=value?1:0}return mask}
export function alignedMaskCoordinates(a,b,tolerance=1e-7){if(!a||!b)return null;if(a.crs!==b.crs)return false;return a.bounds.length===4&&b.bounds.length===4&&a.bounds.every((v,i)=>Math.abs(v-b.bounds[i])<=tolerance*Math.max(1,Math.abs(v)))}
