import * as ort from './vendor/ort.wasm.min.mjs';
import {inferTiles} from './model-input.js';
ort.env.wasm.numThreads=1;
ort.env.wasm.proxy=false;
ort.env.wasm.wasmPaths=new URL('./vendor/',import.meta.url).href;
let session,manifest;
const progress=(message,fraction)=>postMessage({type:'progress',message,fraction});
async function hash(data){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data))).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function load(){if(session)return;const response=await fetch(new URL('./model/manifest.json',import.meta.url));if(!response.ok)throw new Error('训练模型说明未能读取。');manifest=await response.json();const bytes=new Uint8Array(manifest.bytes);let offset=0,cache=null;try{cache=await caches.open('roofscope-grnet-'+manifest.sha256)}catch{}for(let i=0;i<manifest.parts.length;i++){const part=manifest.parts[i],url=new URL('./model/'+part.file,import.meta.url);let response=await cache?.match(url);if(!response){response=await fetch(url);if(!response.ok)throw new Error('模型下载失败，请检查网络后重试。');try{await cache?.put(url,response.clone())}catch{}}const chunk=new Uint8Array(await response.arrayBuffer());if(chunk.length!==part.bytes||await hash(chunk)!==part.sha256){try{await cache?.delete(url)}catch{}throw new Error('模型文件校验未通过，请重新加载。')}bytes.set(chunk,offset);offset+=chunk.length;progress('下载训练模型 '+Math.round(offset/manifest.bytes*100)+'%',offset/manifest.bytes*.4)}if(await hash(bytes)!==manifest.sha256)throw new Error('完整模型校验失败。');progress('正在初始化 GR-Net…',.42);session=await ort.InferenceSession.create(bytes,{executionProviders:['wasm'],graphOptimizationLevel:'all'});progress('模型就绪，开始逐块分析',.45)}
self.onmessage=async ev=>{try{await load();const {input,width,height}=ev.data,started=performance.now();const result=await inferTiles({input,width,height,session,Tensor:ort.Tensor,tile:manifest.tile_size,threshold:manifest.mask_threshold,onProgress:(done,total)=>progress(`GR-Net 分析 ${done} / ${total} 个影像块`,.45+.55*done/total)});postMessage({type:'result',...result,checkpoint:manifest.checkpoint_sha256,threshold:manifest.mask_threshold,elapsedMs:Math.round(performance.now()-started)},[result.greenMask.buffer,result.roofMask.buffer])}catch(error){postMessage({type:'error',message:error.message??String(error)})}};
