// GeoTIFF decoder preserves scientific bands. Display scaling never changes raw measurements.
export async function readGeoTIFF(file){const tiff=await globalThis.GeoTIFF.fromBlob(file);const image=await tiff.getImage(),width=image.getWidth(),height=image.getHeight(),channels=image.getSamplesPerPixel();if(width*height>16000000)throw new Error('影像超过 1600 万像素，请先切片或使用模型服务分块处理。');if(channels===2)throw new Error('双波段影像需先选择单波段或三波段显示输入。');if(channels>8)throw new Error('当前支持至多 8 波段，请先选择所需波段。');const bands=await image.readRasters();const keys=image.getGeoKeys();let bounds=null,origin=null,resolution=null,rotation=false;try{bounds=image.getBoundingBox();origin=image.getOrigin();resolution=image.getResolution();const transform=image.fileDirectory.getValue('ModelTransformation');rotation=!!transform&&(Math.abs(transform[1])>1e-12||Math.abs(transform[4])>1e-12)}catch{}const crs=keys?.ProjectedCSTypeGeoKey??keys?.GeographicTypeGeoKey??null;return{width,height,channels,bands:Array.from({length:channels},(_,i)=>bands[i]),nodata:image.getGDALNoData(),geo:bounds&&crs&&origin&&resolution?{crs:'EPSG:'+crs,bounds,origin,resolution,rotation}:null,geoKeys:keys}}
export function displayBounds(band,nodata){let min=Infinity,max=-Infinity;const values=[];const step=Math.max(1,Math.floor(band.length/10000));for(let i=0;i<band.length;i+=step){const v=band[i];if(Number.isFinite(v)&&v!==nodata){values.push(v);min=Math.min(min,v);max=Math.max(max,v)}}if(!values.length)return[0,1];if(min>=0&&max<=255&&band instanceof Uint8Array)return[0,255];values.sort((a,b)=>a-b);const low=values[Math.floor((values.length-1)*.02)],high=values[Math.floor((values.length-1)*.98)];return low<high?[low,high]:[min,max>min?max:min+1]}
export function rasterRGBA(raster,order='bgrn',binary=false){const {width,height,bands,nodata}=raster,rgba=new Uint8ClampedArray(width*height*4);const indexes=bands.length===1?[0,0,0]:order==='bgrn'?[2,1,0]:[0,1,2],scales=indexes.map(i=>displayBounds(bands[i],nodata));for(let i=0;i<width*height;i++){let valid=true;for(let c=0;c<3;c++){const v=bands[indexes[c]][i];if(!Number.isFinite(v)||v===nodata)valid=false;const [lo,hi]=scales[c];rgba[4*i+c]=binary?(v>0?255:0):Math.min(255,Math.max(0,Math.round(255*(v-lo)/(hi-lo))))}rgba[i*4+3]=valid?255:0}return rgba}
export function pixelToNative(geo,x,y){if(!geo||geo.rotation)throw new Error('需要无旋转、已配准的地理坐标影像。');return[geo.origin[0]+x*geo.resolution[0],geo.origin[1]+y*geo.resolution[1]]}
export function nativeToPixel(geo,x,y){if(!geo||geo.rotation)throw new Error('需要无旋转、已配准的地理坐标影像。');return[(x-geo.origin[0])/geo.resolution[0],(y-geo.origin[1])/geo.resolution[1]]}
export function transformPoint(crsFrom,crsTo,xy){if(crsFrom===crsTo)return xy;const source=crsFrom.toUpperCase(),target=crsTo.toUpperCase();for(const crs of [source,target]){const id=Number(crs.replace('EPSG:',''));if(id>=32601&&id<=32660)globalThis.proj4.defs(crs,`+proj=utm +zone=${id-32600} +datum=WGS84 +units=m +no_defs`);else if(id>=32701&&id<=32760)globalThis.proj4.defs(crs,`+proj=utm +zone=${id-32700} +south +datum=WGS84 +units=m +no_defs`)}try{return globalThis.proj4(source,target,xy)}catch{throw new Error(`不支持 ${source} 到 ${target} 的坐标转换，请先重投影为 EPSG:4326 / 3857 或 WGS84 UTM。`)}}
export function geoBoundsWGS84(geo){if(geo.rotation)throw new Error('旋转影像需先重投影；不能用矩形叠加冒充正确位置。');const [x1,y1,x2,y2]=geo.bounds,points=[[x1,y1],[x1,y2],[x2,y1],[x2,y2]].map(p=>transformPoint(geo.crs,'EPSG:4326',p));return[[Math.min(...points.map(p=>p[1])),Math.min(...points.map(p=>p[0]))],[Math.max(...points.map(p=>p[1])),Math.max(...points.map(p=>p[0]))]]}
export function matchingGeo(a,b){if(!a||!b)return null;if(a.crs!==b.crs||a.rotation!==b.rotation)return false;return a.origin.every((v,i)=>Math.abs(v-b.origin[i])<=1e-10*Math.max(1,Math.abs(v)))&&a.resolution.every((v,i)=>Math.abs(v-b.resolution[i])<=1e-10*Math.max(1,Math.abs(v)))}
export function temperatureSample(raster,geo,x,y){if(!raster.geo||!geo)throw new Error('温度影像和遥感影像都需要地理坐标。');const native=pixelToNative(geo,x+.5,y+.5),coord=transformPoint(geo.crs,raster.geo.crs,native),px=nativeToPixel(raster.geo,...coord),cx=Math.floor(px[0]),cy=Math.floor(px[1]);if(cx<0||cy<0||cx>=raster.width||cy>=raster.height)return null;const v=raster.bands[0][cy*raster.width+cx];return Number.isFinite(v)&&v!==raster.nodata?v:null}
export function convertTemperature(value,unit,scale=1,offset=0){if(!Number.isFinite(value))return null;const v=value*scale+offset;return unit==='kelvin'?v-273.15:v}
