import test from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {createCanvas,Image,ImageData} from '@napi-rs/canvas';
import {readFileSync} from 'node:fs';
import {indexedDB} from 'fake-indexeddb';
import {fromArrayBuffer} from 'geotiff';
import proj4 from 'proj4';
const root=new URL('../frontend/',import.meta.url);
const window=new Window({url:'http://localhost/roofscope/'});
window.document.write(readFileSync(new URL('index.html',root),'utf8'));
for(const key of ['document','history','location','localStorage','CustomEvent','Event','PointerEvent','File','FileReader'])globalThis[key]=window[key];
globalThis.window=window;globalThis.ImageData=ImageData;globalThis.indexedDB=indexedDB;globalThis.proj4=proj4;globalThis.requestAnimationFrame=callback=>callback();
window.scrollTo=()=>{};
const urls=new Map();let urlIndex=0;
URL.createObjectURL=blob=>{const key='blob:test-'+urlIndex++;urls.set(key,blob);return key};URL.revokeObjectURL=key=>urls.delete(key);
class LocalImage extends Image{set src(path){this.pending=(async()=>{const bytes=path.startsWith('blob:')?Buffer.from(await urls.get(path).arrayBuffer()):path.startsWith('data:')?Buffer.from(path.split(',')[1],'base64'):readFileSync(new URL(path,root));super.src=bytes;})();}async decode(){await this.pending;await super.decode();}}
globalThis.Image=LocalImage;
const natives=new WeakMap();
function native(c){let n=natives.get(c);if(!n){n=createCanvas(c.width,c.height);natives.set(c,n)}if(n.width!==c.width)n.width=c.width;if(n.height!==c.height)n.height=c.height;return n}
window.HTMLCanvasElement.prototype.getContext=function(){const ctx=native(this).getContext('2d');return new Proxy(ctx,{get(t,p){if(p==='drawImage')return(img,...args)=>t.drawImage(img instanceof window.HTMLCanvasElement?native(img):img,...args);const value=Reflect.get(t,p,t);return typeof value==='function'?value.bind(t):value},set(t,p,v){t[p]=v;return true}})};
window.HTMLCanvasElement.prototype.toDataURL=function(){return native(this).toDataURL('image/png')};
window.HTMLCanvasElement.prototype.toBlob=function(cb){cb(new Blob([native(this).toBuffer('image/png')],{type:'image/png'}))};
window.HTMLCanvasElement.prototype.getBoundingClientRect=function(){return {left:0,top:0,width:this.width,height:this.height}};
window.HTMLCanvasElement.prototype.setPointerCapture=()=>{};
const nativeFetch=globalThis.fetch;
globalThis.fetch=async url=>{if(String(url).startsWith('data:'))return nativeFetch(url);if(String(url).startsWith('http'))throw new Error('External calls disabled in UI tests');return new Response(readFileSync(new URL(url,root)))};
globalThis.GeoTIFF={fromBlob:async file=>{let buffer;if(file instanceof Blob)buffer=await file.arrayBuffer();else buffer=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsArrayBuffer(file)});return fromArrayBuffer(buffer)}};
await import('../frontend/app.js');
const api=window.roofscope,$=api.$,ext=window.roofscopeExtra;
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
const input=(path,name)=>new window.File([readFileSync(new URL(path,root))],name,{type:'image/png'});
test('Startup consumes real masks and labels their source',()=>{assert.ok(api.state.result,'Sample failed: '+$('toast').textContent);assert.equal(api.state.result.source,'数据集人工标注');close(api.state.result.coverage,1056/32588*100);assert.equal(api.state.result.counts.greenPixels,1056);assert.equal(api.state.result.counts.regionPixels,90000);});
test('Both denominator choices update the visible result',()=>{$('coverageBasis').value='region';$('coverageBasis').onchange();close(api.state.result.coverage,1056/90000*100);$('coverageBasis').value='roof';$('coverageBasis').onchange();});
test('Artificial mask brush edits are reversible',()=>{$('toggleEdit').onclick();const before=api.state.result.greenMask.slice();$('brushTool').value='green-erase';const c=$('imageCanvas'),i=before.indexOf(1),scale=c.width/300;const x=(i%300+.5)*scale,y=(Math.floor(i/300)+.5)*scale;c.dispatchEvent(new window.PointerEvent('pointerdown',{clientX:x,clientY:y,pointerId:1,bubbles:true}));c.dispatchEvent(new window.PointerEvent('pointerup',{clientX:x,clientY:y,pointerId:1,bubbles:true}));assert.ok(api.state.result.counts.greenPixels<1056);$('undoEdit').onclick();assert.deepEqual(api.state.result.greenMask,before);$('toggleEdit').onclick();});
test('Manual samples reject missing coverage and statistics reject mixed bases',()=>{api.state.rows=[10,20,30,40,50].map((coverage,i)=>({id:String(i),city:'深圳',date:'2026-10-01',scale:'100m',basis:'roof',source:'UI test',coverage,lst:35-i}));api.updateSamples();api.computeStats(false);assert.equal(api.state.stats.grade,'优');api.state.rows[0].basis='region';api.computeStats(false);assert.equal(api.state.stats,null);api.state.rows[0].basis='roof';api.computeStats(false);});
test('Project save and reload preserve image, masks, samples and raw temperatures',async()=>{ext.temperature={width:2,height:1,channels:1,bands:[Float32Array.from([300,NaN])],nodata:NaN,geo:null};$('projectName').value='端到端验证';await $('saveProject').onclick();assert.match($('projectSaveStatus').textContent,/保存/);const store=await import('../frontend/project-store.js'),saved=await store.getProject(ext.projectId);assert.equal(saved.result.greenMask.length,90000);api.state.result=null;api.state.rows=[];assert.equal(await ext.restoreLastProject(),true);close(api.state.result.coverage,1056/32588*100);assert.equal(api.state.rows.length,5);assert.ok(Number.isNaN(ext.temperature.bands[0][1]));});
test('Batch pairs file names, analyzes original masks and restores workspace',async()=>{api.state.rows=[];const files=[input('dataset/15-rgb.png','15.png'),input('dataset/15-building.png','15_building_mask.png'),input('dataset/15-green.png','15_mask.png')];await $('batchInput').onchange({target:{files,value:''}});assert.equal(ext.batch.length,1);$('batchMode').value='mask';await $('runBatch').onclick();assert.equal(ext.batch[0].status,'完成',ext.batch[0].reason);close(ext.batch[0].counts.roofCoverage,1681/16749*100);close(api.state.result.coverage,1056/32588*100);assert.equal(ext.batchBusy,false);});
test('Temperature pairing enforces acquisition dates and deduplicates LST pixels',()=>{api.state.rows=[];api.state.demoRows=false;$('imageDate').value='2026-10-01';$('temperatureDate').value='2026-09-30';ext.temperature={width:300,height:300,channels:1,bands:[new Float32Array(90000).fill(300)],nodata:-9999,geo:api.state.geo};ext.temperatureName='test-only.tif';$('temperatureUnit').value='kelvin';$('temperatureScale').value='1';$('temperatureOffset').value='0';$('temperatureScope').value='100px test grid';$('temperatureBasis').value='region';$('spatialUnit').value='grid';$('gridPixels').value='100';$('pairTemperature').onclick();assert.equal(api.state.rows.length,0);assert.match($('toast').textContent,/日期不一致/);$('temperatureDate').value='2026-10-01';$('pairTemperature').onclick();assert.equal(api.state.rows.length,9,$('toast').textContent);for(const row of api.state.rows){close(row.lst,26.85);assert.equal(row.temperaturePixels,10000)}const count=api.state.rows.length;$('pairTemperature').onclick();assert.equal(api.state.rows.length,count);assert.match($('toast').textContent,/已有同名/);});
test('Model inference requires reachable ready service',async()=>{$('serviceURL').value='https://invalid.example';await assert.rejects(()=>ext.runModel(),/External calls disabled/);assert.equal(api.state.result.source,'数据集人工标注');});
test.after(()=>window.happyDOM.abort());
